openapi: 3.0.3
info:
  description: "API para gestionar usuarios, fichajes, trabajos y claves API"
  title: API de Fichajes
  version: 1.0.0
servers:
- url: /
paths:
  /usuarios:
    get:
      operationId: usuariosGET
      responses:
        "200":
          description: OK
      summary: Listar usuarios
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: usuariosPOST
      responses:
        "201":
          description: Creado
      summary: Crear usuario
      x-eov-operation-handler: controllers/DefaultController
  /usuarios/{id}:
    delete:
      operationId: usuariosIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Eliminado
      summary: Borrar usuario
      x-eov-operation-handler: controllers/DefaultController
    get:
      operationId: usuariosIdGET
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Obtener usuario
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: usuariosIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Actualizado
      summary: Actualizar usuario
      x-eov-operation-handler: controllers/DefaultController
  /fichajes:
    get:
      operationId: fichajesGET
      responses:
        "200":
          description: OK
      summary: Listar fichajes
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: fichajesPOST
      responses:
        "201":
          description: Creado
      summary: Crear fichaje
      x-eov-operation-handler: controllers/DefaultController
  /fichajes/{id}:
    delete:
      operationId: fichajesIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Eliminado
      summary: Borrar fichaje
      x-eov-operation-handler: controllers/DefaultController
    get:
      operationId: fichajesIdGET
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Obtener fichaje
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: fichajesIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Actualizado
      summary: Actualizar fichaje
      x-eov-operation-handler: controllers/DefaultController
  /trabajos:
    get:
      operationId: trabajosGET
      responses:
        "200":
          description: OK
      summary: Listar trabajos
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: trabajosPOST
      responses:
        "201":
          description: Creado
      summary: Crear trabajo
      x-eov-operation-handler: controllers/DefaultController
  /trabajos/{id}:
    delete:
      operationId: trabajosIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Eliminado
      summary: Borrar trabajo
      x-eov-operation-handler: controllers/DefaultController
    get:
      operationId: trabajosIdGET
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Obtener trabajo
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: trabajosIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Actualizado
      summary: Actualizar trabajo
      x-eov-operation-handler: controllers/DefaultController
  /apikey:
    get:
      operationId: apikeyGET
      responses:
        "200":
          description: OK
      summary: Listar apikeys
      x-eov-operation-handler: controllers/DefaultController
    post:
      operationId: apikeyPOST
      responses:
        "201":
          description: Creado
      summary: Crear apikey
      x-eov-operation-handler: controllers/DefaultController
  /apikey/{id}:
    delete:
      operationId: apikeyIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Eliminado
      summary: Borrar apikey
      x-eov-operation-handler: controllers/DefaultController
    get:
      operationId: apikeyIdGET
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Obtener apikey
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: apikeyIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Actualizado
      summary: Actualizar apikey
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas: {}
